// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAj_oK0qHoNn8CxEEKp_J2xIwAFSE8s0s',
    appId: '1:75224060571:web:f55d7f9a466631e6f86c3e',
    messagingSenderId: '75224060571',
    projectId: 'doctor-appointment-app-40be6',
    authDomain: 'doctor-appointment-app-40be6.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-40be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_1nqVk4rtSjNGy8uQ7g8-joBR3Yh484',
    appId: '1:75224060571:ios:6b4b180eee87dd38f86c3e',
    messagingSenderId: '75224060571',
    projectId: 'doctor-appointment-app-40be6',
    storageBucket: 'doctor-appointment-app-40be6.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_1nqVk4rtSjNGy8uQ7g8-joBR3Yh484',
    appId: '1:75224060571:ios:6b4b180eee87dd38f86c3e',
    messagingSenderId: '75224060571',
    projectId: 'doctor-appointment-app-40be6',
    storageBucket: 'doctor-appointment-app-40be6.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAj_oK0qHoNn8CxEEKp_J2xIwAFSE8s0s',
    appId: '1:75224060571:web:8fb71e338c2d8772f86c3e',
    messagingSenderId: '75224060571',
    projectId: 'doctor-appointment-app-40be6',
    authDomain: 'doctor-appointment-app-40be6.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-40be6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7A4Fx662YqcZduY49kqoyRe06AnKUBgg',
    appId: '1:75224060571:android:83d41099761318b4f86c3e',
    messagingSenderId: '75224060571',
    projectId: 'doctor-appointment-app-40be6',
    storageBucket: 'doctor-appointment-app-40be6.firebasestorage.app',
  );

}